alter table "TREVISAO"."ENDERECO" add constraint FK_ENDERECO foreign key("IDCLIENTE") references "TREVISAO"."CLIENTE"("ID");
alter table "TREVISAO"."TELEFONE" add constraint FK_TELEFONE foreign key("IDCLIENTE") references "TREVISAO"."CLIENTE"("ID");

--CRUD CLIENTE
INSERT INTO TREVISAO.CLIENTE(ID,MATRICULA,NOME) VALUES (TREVISAO.SEQ_CLIENTE.NEXTVAL, 'RODRIGOE','01');
SELECT ID, MATRICULA, NOME FROM TREVISAO.CLIENTE;
UPDATE TREVISAO.CLIENTE SET MATRICULA = '2', NOME = 'RODRIGO' WHERE ID = 1;
DELETE FROM TREVISAO.CLIENTE WHERE ID = 1;


--CRUD ENDERECO
INSERT INTO TREVISAO.ENDERECO(ID,IDCLIENTE,LOGRADOURO,COMPLEMENTO,NUMERO,BAIRRO,CIDADE,UF,CEP) VALUES (TREVISAO.SEQ_ENDERECO.NEXTVAL,1,'RUADOMONTE','PROXIMOADEFESACIVIL','161','FANCHEM','QUEIMADOS','RJ','666666');
SELECT ID,IDCLIENTE,LOGRADOURO,COMPLEMENTO,NUMERO,BAIRRO,CIDADE,UF,CEP FROM TREVISAO.ENDERECO;
UPDATE TREVISAO.ENDERECO SET LOGRADOURO = 'NAOPOSSUI', COMPLEMENTO = 'MORRODATORRE' WHERE ID = 1;
DELETE FROM TREVISAO.ENDERECO WHERE ID = 1;


--CRUD TELEFONE
INSERT INTO TREVISAO.TELEFONE(ID,IDCLIENTE,DDD,NUMERO) VALUES (TREVISAO.SEQ_TELEFONE.NEXTVAL,1,21,999666000);
SELECT ID,IDCLIENTE,DDD,NUMERO FROM TREVISAO.TELEFONE;
UPDATE TREVISAO.TELEFONE SET NUMERO = 36990000 WHERE ID = 1;
DELETE FROM TREVISAO.TELEFONE WHERE ID = 1;


